/* global POSTERS */
const POSTERS = [
  {
    id: 'robot-01',
    title: 'Cyborg Dreams',
    series: '3D Series',
    year: '2024',
    medium: 'Cinema 4D · Redshift · Photoshop',
    tags: ['3D', 'Character', 'Render'],
    description: 'A hyperchrome figure caught between states — industrial and organic. Part of an ongoing series exploring posthuman aesthetics through glossy material studies and a single dramatic light source.',
    src: '../Portafolio_v2/img/projects/mosaic-robot.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'metaball-01',
    title: 'Liquid Chrome',
    series: '3D Series',
    year: '2024',
    medium: 'Cinema 4D · Redshift',
    tags: ['3D', 'Abstract', 'Materials'],
    description: 'Mercury in free fall, frozen at peak instability. The metaball rig was built to simulate natural fluid dynamics — then aggressively rendered in deep black to strip all warmth out.',
    src: '../Portafolio_v2/img/projects/mosaic-metaball.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'candy-gun-01',
    title: 'Sugar Rush',
    series: '3D Series',
    year: '2023',
    medium: 'Cinema 4D · Redshift',
    tags: ['3D', 'Still Life', 'Candy'],
    description: 'Hard objects turned soft, sharp things made sweet. A commentary on consumer aesthetics — rendered with confectionery textures and candy-shop lighting that makes the dangerous look edible.',
    src: '../Portafolio_v2/img/projects/mosaic-candy-gun.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'aztec-01',
    title: 'Sol Antiguo',
    series: '3D Series',
    year: '2023',
    medium: 'Cinema 4D · Redshift · Photoshop',
    tags: ['3D', 'Cultural', 'Architecture'],
    description: 'A dialogue between pre-Columbian geometry and contemporary CGI. Sourced from memory and fieldwork between Mexico City and Mainz — rendered cold, served as poster.',
    src: '../Portafolio_v2/img/projects/mosaic-aztec.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'frog-01',
    title: 'Ribbit',
    series: '3D Series',
    year: '2022',
    medium: 'Cinema 4D · Redshift',
    tags: ['3D', 'Character', 'Nature'],
    description: 'The frog as icon — hyperreal yet clearly constructed. Surface tension, subsurface scatter, and a single dramatic light source turn the mundane into the monumental.',
    src: '../Portafolio_v2/img/projects/mosaic-frog.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'smile-01',
    title: 'Acid Smile',
    series: '3D Series',
    year: '2023',
    medium: 'Cinema 4D · Redshift',
    tags: ['3D', 'Typography', 'Abstract'],
    description: 'When the smile becomes a texture, a product, a logo. An experiment in rendering expression as commodity — everything grinning, nothing meaning it.',
    src: '../Portafolio_v2/img/projects/mosaic-smile.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'sweet-01',
    title: 'Sweet Lure',
    series: '3D Series',
    year: '2022',
    medium: 'Cinema 4D · Redshift',
    tags: ['3D', 'Still Life', 'Abstract'],
    description: 'Pastel excess. The piece started as a product visualization and became something more uncomfortable — sweetness as seduction, desirability as trap.',
    src: '../Portafolio_v2/img/projects/mosaic-sweet.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'aeroleaf-01',
    title: 'AeroLeaf I',
    series: 'Branding Series',
    year: '2023',
    medium: 'Illustrator · Photoshop · After Effects',
    tags: ['Branding', 'Identity', 'Print'],
    description: 'Identity system for an imagined sustainable mobility brand. The leaf-wing mark was designed for maximum legibility at micro and macro scale across all substrates.',
    src: '../Portafolio_v2/img/projects/AeroLeaf_01.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'aeroleaf-02',
    title: 'AeroLeaf II',
    series: 'Branding Series',
    year: '2023',
    medium: 'Illustrator · Photoshop',
    tags: ['Branding', 'Packaging', 'Print'],
    description: 'Product application and packaging explorations for the AeroLeaf system. Emphasis on sustainable materials language — minimal ink, maximum shelf presence.',
    src: '../Portafolio_v2/img/projects/AeroLeaf_02.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'aeroleaf-03',
    title: 'AeroLeaf III',
    series: 'Branding Series',
    year: '2023',
    medium: 'Illustrator · Photoshop · Cinema 4D',
    tags: ['Branding', '3D', 'Environments'],
    description: 'Branded environment and vehicle mockups. The final chapter of the AeroLeaf story — world-building through graphics, rendered and placed in real contexts.',
    src: '../Portafolio_v2/img/projects/AeroLeaf_03.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'nordwand-01',
    title: 'NordWand I',
    series: 'Photography',
    year: '2022',
    medium: 'Sony A7 III · Lightroom',
    tags: ['Photography', 'Landscape', 'Editorial'],
    description: 'The north wall series documents vertical limestone faces of the Rheinland — shot at golden hour with intentional overexposure in the highlights to flatten depth into pure form.',
    src: '../Portafolio_v2/img/projects/NordWand_01.webp',
  },
  {
    id: 'nordwand-02',
    title: 'NordWand II',
    series: 'Photography',
    year: '2022',
    medium: 'Sony A7 III · Lightroom',
    tags: ['Photography', 'Architecture', 'B&W'],
    description: 'Interior architectures abstracted into graphic planes. Inspired by Sudek and his sense of quiet — light treated as material, shadow treated as negative space.',
    src: '../Portafolio_v2/img/projects/NordWand_02.webp',
  },
  {
    id: 'nordwand-03',
    title: 'NordWand III',
    series: 'Photography',
    year: '2022',
    medium: 'Sony A7 III · Lightroom',
    tags: ['Photography', 'Landscape', 'Color'],
    description: 'The closing frame — a single long exposure made at dusk when the stone turns violet and the horizon drops below it. The whole series ends here.',
    src: '../Portafolio_v2/img/projects/NordWand_03.webp',
  },
  {
    id: 'sussmund-01',
    title: 'Süssmund I',
    series: 'Branding Series',
    year: '2022',
    medium: 'Illustrator · InDesign · Photoshop',
    tags: ['Branding', 'Typography', 'Packaging'],
    description: 'A confectionery brand rooted in German baking tradition. The identity balances nostalgic warmth with contemporary geometry — built around a custom logotype treatment.',
    src: '../Portafolio_v2/img/projects/Sussmund_01.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'sussmund-02',
    title: 'Süssmund II',
    series: 'Branding Series',
    year: '2022',
    medium: 'Illustrator · InDesign',
    tags: ['Branding', 'Print', 'Identity'],
    description: 'Stationery, packaging, and printed collateral for Süssmund. Each piece designed as a tactile object — with debossed seals and uncoated stock as the intended canvas.',
    src: '../Portafolio_v2/img/projects/Sussmund_02.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
  {
    id: 'sussmund-03',
    title: 'Süssmund III',
    series: 'Branding Series',
    year: '2022',
    medium: 'Illustrator · Photoshop · Cinema 4D',
    tags: ['Branding', '3D', 'Mockup'],
    description: 'Final environment explorations — bakery signage, window displays, and campaign imagery. The brand placed in the wild, in Mainz, rendered and photographed.',
    src: '../Portafolio_v2/img/projects/Sussmund_03.webp',
    link: 'https://www.behance.net/hectoruribe2',
  },
];
